site_name: dan_friedman_learnings
site_description: Dan Friedman tutorials and articles on programming & data
site_url: https://dfrieds.com
site_author: Dan Friedman
copyright: Copyright &copy; 2023 Dan Friedman
repo_url: https://github.com/frieds/frieds.github.io

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - mkdocs-jupyter:
      execute: false
      allow_errors: true
      execute_ignore:
        - "python/intermediate_concepts/intro-multithreading-and-multiprocessing.ipynb"
