site_name: dan_friedman_learnings
site_description: Dan Friedman tutorials and articles on programming & data
site_url: https://dfrieds.com
site_author: Dan Friedman
copyright: Copyright &copy; 2023 Dan Friedman
repo_url: https://github.com/frieds/frieds.github.io

use_directory_urls: false


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - mkdocs-jupyter:
      execute: false
      allow_errors: true
      execute_ignore:
        - "python/intro-multithreading-and-multiprocessing.ipynb"

nav:
  - about-me-and-the-site: index.md
  - data-visualizations:
      - matplotlib_plotting:
          - style-plots-python-matplotlib: data-visualizations/style-plots-python-matplotlib.ipynb
          - style-line-plots-python-matplotlib: data-visualizations/style-line-plots-python-matplotlib.ipynb
          - line-plots-python-matplotlib: data-visualizations/line-plots-python-matplotlib.ipynb
          - customize-scatter-plot-styles-python-matplotlib: data-visualizations/customize-scatter-plot-styles-python-matplotlib.ipynb
          - scatter-plots-python-matplotlib: data-visualizations/scatter-plots-python-matplotlib.ipynb
      - pandas_plot:
          - line-plot-python-pandas: data-visualizations/line-plot-python-pandas.ipynb
          - histogram-plot-python-pandas: data-visualizations/histogram-plot-python-pandas.ipynb
          - bar-plot-python-pandas: data-visualizations/bar-plot-python-pandas.ipynb
      - best_practices:
          - how-format-large-tick-values: data-visualizations/how-format-large-tick-values.ipynb
          - when-use-vertical-grouped-barplots: data-visualizations/when-use-vertical-grouped-barplots.ipynb
          - when-use-box-plots: data-visualizations/when-use-box-plots.ipynb
          - when-use-scatter-plot: data-visualizations/when-use-scatter-plot.ipynb
          - when-use-histogram: data-visualizations/when-use-histogram.ipynb
          - when-use-log-scale: data-visualizations/when-use-log-scale.ipynb
          - when-use-heatmaps: data-visualizations/when-use-heatmaps.ipynb
          - when-use-cumulative-frequency-graph: data-visualizations/when-use-cumulative-frequency-graph.ipynb
          - when-use-pie-chart: data-visualizations/when-use-pie-chart.ipynb
          - when-use-vertical-bar-chart: data-visualizations/when-use-vertical-bar-chart.ipynb
          - visualize-historical-time-comparisons: data-visualizations/visualize-historical-time-comparisons.ipynb
          - when-use-vertical-stacked-bar-charts: data-visualizations/when-use-vertical-stacked-bar-charts.ipynb
          - when-use-categorical-scatterplots: data-visualizations/when-use-categorical-scatterplots.ipynb
          - when-use-line-plots: data-visualizations/when-use-line-plots.ipynb
          - when-use-horizontal-bar-charts: data-visualizations/when-use-horizontal-bar-charts.ipynb
  - python:
      - intermediate_concepts:
          - list-comprehensions: python/list-comprehensions.ipynb
          - intro-to-apis: python/intro-to-apis.ipynb
          - intro-multithreading-and-multiprocessing: python/intro-multithreading-and-multiprocessing.ipynb
          - design-classes: python/design-classes.ipynb
      - beginner_concepts:
          - string-formatting: python/string-formatting.ipynb
          - incremental-development: python/incremental-development.ipynb
          - string-methods: python/string-methods.ipynb
          - list-methods: python/list-methods.ipynb
          - math-operations: python/math-operations.ipynb
          - conditional-logic-if-statements: python/conditional-logic-if-statements.ipynb
          - lists: python/lists.ipynb
          - tuples: python/tuples.ipynb
          - enumerate-function: python/enumerate-function.ipynb
          - iterate-using-for-and-while-loops: python/iterate-using-for-and-while-loops.ipynb
          - functions-generalization: python/functions-generalization.ipynb
          - functions: python/functions.ipynb
          - docstrings-functions: python/docstrings-functions.ipynb
          - types-and-values: python/types-and-values.ipynb
          - fundamental-programming-terms: python/fundamental-programming-terms.ipynb
          - count-occurences-each-unique-element-in-list: python/count-occurences-each-unique-element-in-list.ipynb
          - dictionaries: python/dictionaries.ipynb
          - dictionary-methods: python/dictionary-methods.ipynb
          - guessing-game-with-keyboard-input: python/guessing-game-with-keyboard-input.ipynb
          - strings: python/strings.ipynb
          - zip-function: python/zip-function.ipynb
          - read-in-csv-files: python/read-in-csv-files.ipynb
          - validate-function-arguments: python/validate-function-arguments.ipynb
      - beginner_algorithms:
          - two-sums2: python/two-sums2.ipynb
          - unique-number-of-occurences-python: python/unique-number-of-occurences-python.ipynb
          - find-words-formed-by-characters: python/find-words-formed-by-characters.ipynb
          - how-many-numbers-smaller-than-current-number: python/how-many-numbers-smaller-than-current-number.ipynb
          - rank-transform-array: python/rank-transform-array.ipynb
          - check-if-double-exists: python/check-if-double-exists.ipynb
          - two-sums-python: python/two-sums-python.ipynb
          - longest-common-prefix-python: python/longest-common-prefix-python.ipynb
          - partition-array-three-equal-sums: python/partition-array-three-equal-sums.ipynb
          - subtract-product-sum-of-digits: python/subtract-product-sum-of-digits.ipynb
          - number-steps-reduce-number-to-zero: python/number-steps-reduce-number-to-zero.ipynb
          - height-checker: python/height-checker.ipynb
          - valid-parentheses-python: python/valid-parentheses-python.ipynb
          - find-numbers-disappeared-in-array: python/find-numbers-disappeared-in-array.ipynb
          - largest-substring-python: python/largest-substring-python.ipynb
          - create-target-array-given-order: python/create-target-array-given-order.ipynb
          - minimum-absolute-difference: python/minimum-absolute-difference.ipynb
          - jewels-and-stones-python: python/jewels-and-stones-python.ipynb
          - sorted-squares: python/sorted-squares.ipynb
          - intersection-two-arrays: python/intersection-two-arrays.ipynb
      - advanced_algorithms:
          - median-two-sorted-arrays-python: python/median-two-sorted-arrays-python.ipynbdf
      - intermediate_algorithms:
          - cl-minesweeper: python/cl-minesweeper.ipynb
  - math:
      - miscellaneous:
          - intro-math-symbols: math/intro-math-symbols.ipynb
      - inferential_statistics:
          - z-tests: math/z-tests.ipynb
          - independent-samples-t-test: math/independent-samples-t-test.ipynb
          - correlation-does-not-imply-causation: math/correlation-does-not-imply-causation.ipynb
          - errors-hypothesis-testing: math/errors-hypothesis-testing.ipynb
          - dependent-samples-t-test: math/dependent-samples-t-test.ipynb
          - intro-t-test-terms-and-one-sample-test: math/intro-t-test-terms-and-one-sample-test.ipynb
          - confidence-intervals: math/confidence-intervals.ipynb
          - effect-size: math/effect-size.ipynb
      - descriptive_statistics:
          - skewness: math/skewness.ipynb
          - pearsons-correlation-coefficient: math/pearsons-correlation-coefficient.ipynb
          - outliers: math/outliers.ipynb
          - central-limit-theorem: math/central-limit-theorem.ipynb
          - z-scores: math/z-scores.ipynb
          - bessels-correction: math/bessels-correction.ipynb
          - mean-median-mode: math/mean-median-mode.ipynb
          - standard-deviation: math/standard-deviation.ipynb
          - correlation: math/correlation.ipynb
          - spearmans-correlation: math/spearmans-correlation.ipynb
      - distributions:
          - normal-distribution: math/normal-distribution.ipynb
          - exponential-distribution: math/exponential-distribution.ipynb
          - probability-plot: math/probability-plot.ipynb
  - teaching:
        - 2018-summer-msis-2629-syllabus: teaching/2018-summer-msis-2629-syllabus.ipynb
  - data-analysis:
      - data_wrangling:
          - bin-values-python-pandas: data-analysis/bin-values-python-pandas.ipynb
          - create-new-column-python-pandas: data-analysis/create-new-column-python-pandas.ipynb
          - groupby-python-pandas: data-analysis/groupby-python-pandas.ipynb
          - categorical-data-python-pandas: data-analysis/categorical-data-python-pandas.ipynb
          - pivot-python-pandas: data-analysis/pivot-python-pandas.ipynb
          - value-counts-python-pandas: data-analysis/value-counts-python-pandas.ipynb
          - rank-method-python-pandas: data-analysis/rank-method-python-pandas.ipynb
          - pivot-table-python-pandas: data-analysis/pivot-table-python-pandas.ipynb
          - create-year-month-column: data-analysis/create-year-month-column.ipynb
          - self-join-python-pandas: data-analysis/self-join-python-pandas.ipynb
          - query-python-pandas: data-analysis/query-python-pandas.ipynb
          - melt-unpivot-python-pandas: data-analysis/melt-unpivot-python-pandas.ipynb
          - crosstabs-python-pandas: data-analysis/crosstabs-python-pandas.ipynb
          - shift-method-python-pandas: data-analysis/shift-method-python-pandas.ipynb
      - business_metrics:
          - popular-summary-business-metrics: data-analysis/popular-summary-business-metrics.ipynb
  - article:
      - data-science-as-a-career-path: article/data-science-as-a-career-path.md
      - scientific-method-driven-product-development: article/scientific-method-driven-product-development.md
  - machine-learning:
      - classification:
          - visual-introduction-classification-logistic-regression-python: machine-learning/visual-introduction-classification-logistic-regression-python.ipynb
      - clustering:
          - k-means-from-scratch-python: machine-learning/k-means-from-scratch-python.ipynb
          - segmentation-vs-clustering: machine-learning/segmentation-vs-clustering.ipynb


